server {
    listen 80;
    
    # Public Nginx routes / to FRONTEND_PORT
    location / {
        proxy_pass http://frontend:3001;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        
        # Pass original headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 81;
    
    # Public Nginx routes /api/ to BACKEND_PORT, BUT STRIPS "/api" from the URI!
    # So we receive "/auth/login", and must rewrite it back to "/api/auth/login" for Next.js
    location / {
        rewrite ^/(.*) /api/$1 break;
        proxy_pass http://frontend:3001;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        
        # Pass original headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
