# Active Profile (Default to dev)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Common Settings
spring.application.name=backend
server.port=8029

# Common Configuration
spring.mvc.static-path-pattern= /**
spring.web.resources.static-locations=file:./upload/

# Jwt Configuration
jwt.secret = ${JWT_SECRET:new_cafe_project_secret_key_which_is_more_than_32_bytes_long_make_sure_to_change_in_production}
jwt.expiration = ${JWT_EXPIRATION:3600000}