# Active Profile (Default to dev)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Common Settings
spring.application.name=backend
server.port=8029

# Common Configuration
spring.mvc.static-path-pattern= /**
spring.web.resources.static-locations=file:./upload/

# Jwt Configuration
jwt.secret = ${JWT_SECRET}
jwt.expiration = ${JWT_EXPIRATION}